# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=300)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('isbn_code', models.CharField(blank=True, help_text=b'Version book works on', max_length=20)),
                ('cover_image', models.ImageField(upload_to=b'images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
